# Generated by Django 6.0.5 on 2026-05-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('primary_color', models.CharField(default='#10b981', max_length=20)),
                ('domain_name', models.CharField(blank=True, max_length=120)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
            },
        ),
    ]
