# Generated by Django 6.0.5 on 2026-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryarea',
            name='estimated_max_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='estimated_min_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated words to match customer location, e.g. kigali, gasabo, nyarutarama', max_length=240),
        ),
    ]
